{
 "title": "POD Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", pod=~\"$service.*\"}, pod)"
   },
   {
    "name": "container",
    "label": "container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$service.*\", pod=~\"$pod\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "POD Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$service.*\", pod=~\"$pod\", container!=\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "POD Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "POD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$service.*\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", pod=~\"$service.*\", pod=~\"$pod\", container!=\"POD\", container!=\"\"})",
     "legendFormat": "container request"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\"$service.*\", pod=~\"$pod\", container!=\"POD\", container!=\"\"})",
     "legendFormat": "container limit"
    }
   ]
  },
  {
   "title": "POD Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", image!=\"\", pod=~\"$service.*\", pod=~\"$pod\", container!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\", container!=\"\", container!=\"POD\"}",
     "legendFormat": "container limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\", container!=\"\", container!=\"POD\"}",
     "legendFormat": "container request"
    }
   ]
  },
  {
   "title": "Container Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", pod=~\"$pod\", pod=~\"$service.*\", container!=\"POD\", container!=\"\", container=~\"$container\"}[5m])",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", pod=~\"$service.*\", container!=\"POD\", container!=\"\", image!=\"\"}"
      }
     ]
    }
   ]
  }
 ]
}