{
 "title": "Http Requests Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "method",
    "label": "method",
    "query": "label_values(performance_test_requests{}, method)"
   },
   {
    "name": "url",
    "label": "url",
    "query": "label_values(performance_test_requests{}, url)"
   },
   {
    "name": "traceId",
    "label": "traceId",
    "query": "label_values(performance_test_requests{}, traceId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(performance_test_requests{method=~\"$method\", url=~\"$url\", status=\"Inprogress\", traceId=~\"$traceId\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Inprogress Requests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "performance_test_inprogress_requests{url=~\"$url\"}"
    }
   ]
  },
  {
   "title": "Total Success Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(performance_test_requests{method=~\"$method\", url=~\"$url\", status=\"success\", traceId=~\"$traceId\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Failed Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(performance_test_requests{method=~\"$method\", url=~\"$url\", status=\"failed\", traceId=~\"$traceId\"}[$__range]))"
    }
   ]
  }
 ]
}