apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: performance-test
  template:
    metadata:
      labels:
        app: performance-test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: performance-test
        image: performance-test:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          - name: Game_Host
            value: rock-paper-scissors
          - name: Game_Port
            value: "5000"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: performance-test
spec:
  selector:
    app: performance-test
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: performance-test-mapping
spec:
  prefix: /api/performance-test/
  rewrite: /api/performance-test/
  service: performance-test:8000